import org.peg.String

record Lesson(subject: String, teacher: String, studentGroup: String) {
    injective relation slot: Slot
    injective relation room: Room
}
record Room(identity name: String) {}
record Slot(identity day: String, identity start: LocalTime, identity end: LocalTime) {}

facts {
    Room = { "Room A", "Room B" }
    Slot = {
        ("Monday", (8, 30), (9, 30)),
        ("Monday", (9, 30), (10, 30)),

        ("Tuesday", (8, 30), (9, 30)),
        ("Tuesday", (9, 30), (10, 30)),
    }
    Lesson = {
        ("Math", "A. Turing", "9th grade"),
        ("Math", "A. Turing", "9th grade"),
        ("Biology", "C. Darwin", "9th grade"),
        ("Spanish", "P. Cruz", "9th grade"),
        ("Math", "A. Turing", "10th grade"),
        ("Math", "A. Turing", "10th grade"),
        ("Geography", "C. Darwin", "10th grade"),
        ("Spanish", "P. Cruz", "10th grade"),
    }
}

constraint {
    forall l1, l2 in Lesson:
        (l1 != l2 and l1.slot = l2.slot) implies
            (l1.room != l2.room and l1.teacher != l2.teacher and l1.studentGroup != l2.studentGroup)
}
// (not (l1 != l2 and l2.slot == l2.slot)) or (l1.room != l2.room and l1.teacher != l2.teacher and l1.studentGroup != l2.studentGroup)
// not (l1 != l2) OR l1.slot == l2.slot) or (l1.room != l2.room and l1.teacher != l2.teacher and l1.studentGroup != l2.studentGroup)

// for all l1 in lesson:
// for all l2 in lesson:
// /\ (not (l1 != l2) or l1.slot == l2.slot) or l1.room != l2.room)
// /\ (not (l1 != l2) or l1.slot == l2.slot) or l1.teacher != l2.teacher)
// /\ (not (l1 != l2) or l1.slot == l2.slot) or l1.studentGroup != l2.studentGroup)