import org.peg.String
import org.peg.DateTime
import org.peg.Duration

record Lesson(subject: Subject, teacher: Teacher, studentGroup: StudentGroup) {
    injective relation slot: Slot
    injective relation room: Room
}
record StudentGroup(identity name: String)
record Teacher(identity name: String)
record Subject(identity name: String)
record Room(identity name: String)
record Slot(identity day: String, identity start: LocalTime, identity end: LocalTime)

facts {
    Room = { "Room A", "Room B", "Room C" }
    Slot = {
        ("Monday", LocalTime.of(8, 30), LocalTime.of(9, 30)),
        ("Monday", LocalTime.of(9, 30), LocalTime.of(10, 30)),
        ("Monday", LocalTime.of(13, 30), LocalTime.of(14, 30)),
        ("Monday", LocalTime.of(10, 30), LocalTime.of(11, 30)),
        ("Monday", LocalTime.of(14, 30), LocalTime.of(15, 30)),

        ("Tuesday", LocalTime.of(8, 30), LocalTime.of(9, 30)),
        ("Tuesday", LocalTime.of(9, 30), LocalTime.of(10, 30)),
        ("Tuesday", LocalTime.of(10, 30), LocalTime.of(11, 30)),
        ("Tuesday", LocalTime.of(13, 30), LocalTime.of(14, 30)),
        ("Tuesday", LocalTime.of(14, 30), LocalTime.of(15, 30)),
    }
    Lesson = {
        ("Math", "A. Turing", "9th grade"),
        ("Math", "A. Turing", "9th grade"),
        ("Physics", "M. Curie", "9th grade"),
        ("Chemistry", "M. Curie", "9th grade"),
        ("Biology", "C. Darwin", "9th grade"),
        ("History", "I. Jones", "9th grade"),
        ("English", "I. Jones", "9th grade"),
        ("English", "I. Jones", "9th grade"),
        ("Spanish", "P. Cruz", "9th grade"),
        ("Spanish", "P. Cruz", "9th grade"),

        ("Math", "A. Turing", "10th grade"),
        ("Math", "A. Turing", "10th grade"),
        ("Math", "A. Turing", "10th grade"),
        ("Physics", "M. Curie", "10th grade"),
        ("Chemistry", "M. Curie", "10th grade"),
        ("French", "M. Curie", "10th grade"),
        ("Geography", "C. Darwin", "10th grade"),
        ("History", "I. Jones", "10th grade"),
        ("English", "P. Cruz", "10th grade"),
        ("Spanish", "P. Cruz", "10th grade"),
    }
}

constraint {
    forall l1, l2 in Lesson:
        (l1 != l2 and l1.slot == l2.slot) implies
            (l1.room != l2.room and l1.teacher != l2.teacher and l1.studentGroup != l2.studentGroup)
}